name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/turbo
        with:
          task: build

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Workspace check
        run: pnpm run check

      - name: Commitlint
        run: pnpm commitlint --from="${{ github.sha }}"

      - name: ESLint
        uses: ./.github/actions/turbo
        with:
          task: lint

      - name: Prettier
        uses: ./.github/actions/turbo
        with:
          task: format

  typecheck:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up project
        uses: ./.github/actions/setup

      - name: Type check
        uses: ./.github/actions/turbo
        with:
          task: ts
