name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      production:
        description: 'Deploy to production'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for CI checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          match_pattern: '^(build|lint|typecheck)$'

  deploy:
    runs-on: ubuntu-latest
    needs: wait-for-checks
    environment: ${{ inputs.production && 'production' || 'preview' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check production
        run: |
          if [ "${{ inputs.production }}" == "true" ]; then
            # Production deployment must be on main branch
            if [ "${{ github.ref_name }}" != "main" ]; then
              echo -e "\033[0;31mMust be on main branch to deploy to production\033[0m"
              exit 1
            fi
          fi

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build for Vercel
        run: |
          if [ "${{ inputs.production }}" == "true" ]; then
            pnpm vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}" --yes
          else
            pnpm vercel build --token="${{ secrets.VERCEL_TOKEN }}" --yes
          fi

      - name: Deploy to Vercel
        run: |
          if [ "${{ inputs.production }}" == "true" ]; then
            pnpm vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
          else
            pnpm vercel deploy --prebuilt --token="${{ secrets.VERCEL_TOKEN }}"
          fi
